// Generated by gencpp from file timoo_msgs/timooStatus.msg
// DO NOT EDIT!


#ifndef TIMOO_MSGS_MESSAGE_TIMOOSTATUS_H
#define TIMOO_MSGS_MESSAGE_TIMOOSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>

namespace timoo_msgs
{
template <class ContainerAllocator>
struct timooStatus_
{
  typedef timooStatus_<ContainerAllocator> Type;

  timooStatus_()
    : header()
    , gps_status(false)
    , gps_timestamp()
    , vertical_angle_list()  {
      vertical_angle_list.assign(0.0);
  }
  timooStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps_status(false)
    , gps_timestamp(_alloc)
    , vertical_angle_list()  {
  (void)_alloc;
      vertical_angle_list.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _gps_status_type;
  _gps_status_type gps_status;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _gps_timestamp_type;
  _gps_timestamp_type gps_timestamp;

   typedef boost::array<float, 16>  _vertical_angle_list_type;
  _vertical_angle_list_type vertical_angle_list;





  typedef boost::shared_ptr< ::timoo_msgs::timooStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::timoo_msgs::timooStatus_<ContainerAllocator> const> ConstPtr;

}; // struct timooStatus_

typedef ::timoo_msgs::timooStatus_<std::allocator<void> > timooStatus;

typedef boost::shared_ptr< ::timoo_msgs::timooStatus > timooStatusPtr;
typedef boost::shared_ptr< ::timoo_msgs::timooStatus const> timooStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::timoo_msgs::timooStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::timoo_msgs::timooStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::timoo_msgs::timooStatus_<ContainerAllocator1> & lhs, const ::timoo_msgs::timooStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gps_status == rhs.gps_status &&
    lhs.gps_timestamp == rhs.gps_timestamp &&
    lhs.vertical_angle_list == rhs.vertical_angle_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::timoo_msgs::timooStatus_<ContainerAllocator1> & lhs, const ::timoo_msgs::timooStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace timoo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::timoo_msgs::timooStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::timoo_msgs::timooStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timoo_msgs::timooStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timoo_msgs::timooStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timoo_msgs::timooStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timoo_msgs::timooStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::timoo_msgs::timooStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db5f4c34cfa1b0d643f4949d2223d340";
  }

  static const char* value(const ::timoo_msgs::timooStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb5f4c34cfa1b0d6ULL;
  static const uint64_t static_value2 = 0x43f4949d2223d340ULL;
};

template<class ContainerAllocator>
struct DataType< ::timoo_msgs::timooStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "timoo_msgs/timooStatus";
  }

  static const char* value(const ::timoo_msgs::timooStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::timoo_msgs::timooStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# timoo LIDAR scan packets.\n"
"\n"
"Header           header         # standard ROS message header\n"
"bool gps_status\n"
"Header gps_timestamp\n"
"float32[16] vertical_angle_list\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::timoo_msgs::timooStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::timoo_msgs::timooStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps_status);
      stream.next(m.gps_timestamp);
      stream.next(m.vertical_angle_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timooStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::timoo_msgs::timooStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::timoo_msgs::timooStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_timestamp: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.gps_timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vertical_angle_list: ";
    if (v.vertical_angle_list.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.vertical_angle_list.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.vertical_angle_list[i]);
    }
    if (v.vertical_angle_list.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIMOO_MSGS_MESSAGE_TIMOOSTATUS_H
