// Generated by gencpp from file timoo_msgs/timooScan.msg
// DO NOT EDIT!


#ifndef TIMOO_MSGS_MESSAGE_TIMOOSCAN_H
#define TIMOO_MSGS_MESSAGE_TIMOOSCAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <timoo_msgs/timooPacket.h>

namespace timoo_msgs
{
template <class ContainerAllocator>
struct timooScan_
{
  typedef timooScan_<ContainerAllocator> Type;

  timooScan_()
    : header()
    , packets()  {
    }
  timooScan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::timoo_msgs::timooPacket_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::timoo_msgs::timooPacket_<ContainerAllocator> >> _packets_type;
  _packets_type packets;





  typedef boost::shared_ptr< ::timoo_msgs::timooScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::timoo_msgs::timooScan_<ContainerAllocator> const> ConstPtr;

}; // struct timooScan_

typedef ::timoo_msgs::timooScan_<std::allocator<void> > timooScan;

typedef boost::shared_ptr< ::timoo_msgs::timooScan > timooScanPtr;
typedef boost::shared_ptr< ::timoo_msgs::timooScan const> timooScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::timoo_msgs::timooScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::timoo_msgs::timooScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::timoo_msgs::timooScan_<ContainerAllocator1> & lhs, const ::timoo_msgs::timooScan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.packets == rhs.packets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::timoo_msgs::timooScan_<ContainerAllocator1> & lhs, const ::timoo_msgs::timooScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace timoo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::timoo_msgs::timooScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::timoo_msgs::timooScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timoo_msgs::timooScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timoo_msgs::timooScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timoo_msgs::timooScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timoo_msgs::timooScan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::timoo_msgs::timooScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "577be07a7422add7a083c04c69c02d07";
  }

  static const char* value(const ::timoo_msgs::timooScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x577be07a7422add7ULL;
  static const uint64_t static_value2 = 0xa083c04c69c02d07ULL;
};

template<class ContainerAllocator>
struct DataType< ::timoo_msgs::timooScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "timoo_msgs/timooScan";
  }

  static const char* value(const ::timoo_msgs::timooScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::timoo_msgs::timooScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# timoo LIDAR scan packets.\n"
"\n"
"Header           header         # standard ROS message header\n"
"timooPacket[] packets        # vector of raw packets\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: timoo_msgs/timooPacket\n"
"# Raw timoo LIDAR packet.\n"
"\n"
"time stamp              # packet timestamp\n"
"uint8[1206] data        # packet contents\n"
"time data_stamp       # packet timestamp[year-month-day-hour form DISOP]\n"
"bool gps_status         # gps status from DISOP\n"
;
  }

  static const char* value(const ::timoo_msgs::timooScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::timoo_msgs::timooScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timooScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::timoo_msgs::timooScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::timoo_msgs::timooScan_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "packets: ";
    if (v.packets.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.packets.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::timoo_msgs::timooPacket_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.packets[i]);
    }
    if (v.packets.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIMOO_MSGS_MESSAGE_TIMOOSCAN_H
