// Generated by gencpp from file timoo_msgs/timooPacket.msg
// DO NOT EDIT!


#ifndef TIMOO_MSGS_MESSAGE_TIMOOPACKET_H
#define TIMOO_MSGS_MESSAGE_TIMOOPACKET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace timoo_msgs
{
template <class ContainerAllocator>
struct timooPacket_
{
  typedef timooPacket_<ContainerAllocator> Type;

  timooPacket_()
    : stamp()
    , data()
    , data_stamp()
    , gps_status(false)  {
      data.assign(0);
  }
  timooPacket_(const ContainerAllocator& _alloc)
    : stamp()
    , data()
    , data_stamp()
    , gps_status(false)  {
  (void)_alloc;
      data.assign(0);
  }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef boost::array<uint8_t, 1206>  _data_type;
  _data_type data;

   typedef ros::Time _data_stamp_type;
  _data_stamp_type data_stamp;

   typedef uint8_t _gps_status_type;
  _gps_status_type gps_status;





  typedef boost::shared_ptr< ::timoo_msgs::timooPacket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::timoo_msgs::timooPacket_<ContainerAllocator> const> ConstPtr;

}; // struct timooPacket_

typedef ::timoo_msgs::timooPacket_<std::allocator<void> > timooPacket;

typedef boost::shared_ptr< ::timoo_msgs::timooPacket > timooPacketPtr;
typedef boost::shared_ptr< ::timoo_msgs::timooPacket const> timooPacketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::timoo_msgs::timooPacket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::timoo_msgs::timooPacket_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::timoo_msgs::timooPacket_<ContainerAllocator1> & lhs, const ::timoo_msgs::timooPacket_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.data == rhs.data &&
    lhs.data_stamp == rhs.data_stamp &&
    lhs.gps_status == rhs.gps_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::timoo_msgs::timooPacket_<ContainerAllocator1> & lhs, const ::timoo_msgs::timooPacket_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace timoo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::timoo_msgs::timooPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::timoo_msgs::timooPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timoo_msgs::timooPacket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::timoo_msgs::timooPacket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timoo_msgs::timooPacket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::timoo_msgs::timooPacket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::timoo_msgs::timooPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ff7fd67e5891b718bf3c74aa9e2559a";
  }

  static const char* value(const ::timoo_msgs::timooPacket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ff7fd67e5891b71ULL;
  static const uint64_t static_value2 = 0x8bf3c74aa9e2559aULL;
};

template<class ContainerAllocator>
struct DataType< ::timoo_msgs::timooPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "timoo_msgs/timooPacket";
  }

  static const char* value(const ::timoo_msgs::timooPacket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::timoo_msgs::timooPacket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Raw timoo LIDAR packet.\n"
"\n"
"time stamp              # packet timestamp\n"
"uint8[1206] data        # packet contents\n"
"time data_stamp       # packet timestamp[year-month-day-hour form DISOP]\n"
"bool gps_status         # gps status from DISOP\n"
;
  }

  static const char* value(const ::timoo_msgs::timooPacket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::timoo_msgs::timooPacket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.data);
      stream.next(m.data_stamp);
      stream.next(m.gps_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct timooPacket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::timoo_msgs::timooPacket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::timoo_msgs::timooPacket_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.data_stamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TIMOO_MSGS_MESSAGE_TIMOOPACKET_H
